import { createServerComponentClient } from "@supabase/auth-helpers-nextjs";
import { cookies } from "next/headers";
import Link from "next/link";
import { PageHeader } from "../../../../components/page-header";
import { PropAssetSwitcher } from "../../../../components/prop-asset-switcher";

export default async function WithdrawPage() {
  const supabase = createServerComponentClient({ cookies });

  return (
    <div className="space-y-8">
      <div className="md:mx-[80px] flex flex-col gap-6">
        <PageHeader
          pageTitle="History"
          link="/real-estate/assets"
          linkTitle="Assets"
        />

        <div className="rounded-3xl bg-[#292929] px-6 py-[35px] flex justify-between items-center mb-6">
          <PropAssetSwitcher />

          <div className="flex space-x-2">
            <Link
              href="/real-estate/assets/withdraw"
              className="bg-white text-black px-4 py-2 rounded-xl"
            >
              Withdraw dividend
            </Link>
            <Link
              href="/real-estate/assets/history"
              className="bg-white text-black px-4 py-2 rounded-xl"
            >
              History
            </Link>
          </div>
        </div>
      </div>

      <div className="rounded-lg p-6">
        <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
          <div className="bg-[#222] p-6 rounded-lg">
            <h2 className="text-xl font-bold mb-6">Request withdrawal</h2>
            <form className="space-y-6">
              <div>
                <label className="block text-sm font-medium mb-2">
                  Withdrawal source
                </label>
                <div className="flex items-center gap-2">
                  <input
                    type="file"
                    placeholder="Property name"
                    className="flex-1 bg-[#292929] rounded-[10px] px-4 py-3"
                  />
                </div>
              </div>

              <div>
                <label className="block text-sm font-medium mb-2">
                  Amount to withdraw
                </label>
                <input
                  type="text"
                  placeholder="Input Your Email"
                  className="w-full bg-[#292929] rounded-[10px] px-4 py-3"
                />
              </div>

              <div>
                <label className="block text-sm font-medium mb-2">
                  Preferred channel
                </label>
                <input
                  type="text"
                  placeholder="Input Your Email"
                  className="w-full bg-[#292929] rounded-[10px] px-4 py-3"
                />
              </div>

              <div>
                <label className="block text-sm font-medium mb-2">
                  Wallet address
                </label>
                <input
                  type="text"
                  placeholder="Input Your Email"
                  className="w-full bg-[#292929] rounded-[10px] px-4 py-3"
                />
              </div>

              <button
                type="submit"
                className="w-full bg-red-500 text-white py-3 rounded-[10px]"
              >
                Submit verification
              </button>
            </form>
          </div>

          <div className="bg-[#222] p-6 rounded-lg h-fit">
            <h2 className="text-xl font-bold mb-4">
              Revenue divident from your active account
            </h2>
            <p className="text-gray-400 mb-4 text-xs">
              As an active investor in our platform, you can earn a regular
              stream of revenue dividends from your investments. These dividends
              are generated from the rental income, interest payments, and other
              cash flows produced by the properties and assets in your
              portfolio. With our revenue dividend program, you can receive a
              quarterly or monthly distribution of income, providing a
              predictable and passive source of returns.
            </p>
            <p className="text-gray-400 text-xs">
              This allows you to benefit from the ongoing cash flow generated by
              your investments in addition to any long-term capital
              appreciation. By choosing to reinvest your dividends, you can also
              take advantage of the power of compounding, potentially
              accelerating the growth of your investment portfolio over time.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
